using Microsoft.EntityFrameworkCore;
using ParksApi.Entities;

namespace ParksApi.Helpers
{
  public class ParksApiContext : DbContext
  {
    public ParksApiContext(DbContextOptions options) : base(options)
    {
    }
    public DbSet<State> States { get; set; }
    public DbSet<Park> Parks { get; set; }
    public DbSet<User> Users { get; set; }
    protected override void OnModelCreating(ModelBuilder builder)
    {
      base.OnModelCreating(builder);
      builder.Entity<State>().HasData(
        new State { StateId = 1, Name = "Alabama", Region = "South" },
        new State { StateId = 2, Name = "Alaska", Region = "West" },
        new State { StateId = 3, Name = "Arizona", Region = "West" },
        new State { StateId = 4, Name = "Arkansas", Region = "South" },
        new State { StateId = 5, Name = "California", Region = "West" },
        new State { StateId = 6, Name = "Colorado", Region = "West" },
        new State { StateId = 7, Name = "Connecticut", Region = "West" },
        new State { StateId = 8, Name = "Delaware", Region = "South" },
        new State { StateId = 9, Name = "Florida", Region = "South" },
        new State { StateId = 10, Name = "Georgia", Region = "South" },
        new State { StateId = 11, Name = "Hawaii", Region = "West" },
        new State { StateId = 12, Name = "Idaho", Region = "West" },
        new State { StateId = 13, Name = "Illinois", Region = "Midwest" },
        new State { StateId = 14, Name = "Indiana", Region = "Midwest" },
        new State { StateId = 15, Name = "Iowa", Region = "Midwest" },
        new State { StateId = 16, Name = "Kansas", Region = "Midwest" },
        new State { StateId = 17, Name = "Kentucky", Region = "South" },
        new State { StateId = 18, Name = "Louisiana", Region = "South" },
        new State { StateId = 19, Name = "Maine", Region = "West" },
        new State { StateId = 20, Name = "Maryland", Region = "South" },
        new State { StateId = 21, Name = "Massachusetts", Region = "Northeast" },
        new State { StateId = 22, Name = "Michigan", Region = "Midwest" },
        new State { StateId = 23, Name = "Minnesota", Region = "Midwest" },
        new State { StateId = 24, Name = "Mississippi", Region = "South" },
        new State { StateId = 25, Name = "Missouri", Region = "Midwest" },
        new State { StateId = 26, Name = "Montana", Region = "West" },
        new State { StateId = 27, Name = "Nebraska", Region = "Midwest" },
        new State { StateId = 28, Name = "Nevada", Region = "West" },
        new State { StateId = 29, Name = "New Hampshire", Region = "Northeast" },
        new State { StateId = 30, Name = "New Jersey", Region = "Northeast" },
        new State { StateId = 31, Name = "New Mexico", Region = "West" },
        new State { StateId = 32, Name = "New York", Region = "Northeast" },
        new State { StateId = 33, Name = "North Carolina", Region = "South" },
        new State { StateId = 34, Name = "North Dakota", Region = "Midwest" },
        new State { StateId = 35, Name = "Ohio", Region = "Midwest" },
        new State { StateId = 36, Name = "Oklahoma", Region = "South" },
        new State { StateId = 37, Name = "Oregon", Region = "West" },
        new State { StateId = 38, Name = "Pennsylvania", Region = "Northeast" },
        new State { StateId = 39, Name = "Rhode Island", Region = "Northeast" },
        new State { StateId = 40, Name = "South Carolina", Region = "South" },
        new State { StateId = 41, Name = "South Dakota", Region = "Midwest" },
        new State { StateId = 42, Name = "Tennessee", Region = "South" },
        new State { StateId = 43, Name = "Texas", Region = "South" },
        new State { StateId = 44, Name = "Utah", Region = "West" },
        new State { StateId = 45, Name = "Vermont", Region = "Northeast" },
        new State { StateId = 46, Name = "Virginia", Region = "South" },
        new State { StateId = 47, Name = "Washington", Region = "West" },
        new State { StateId = 48, Name = "West Virginia", Region = "South" },
        new State { StateId = 49, Name = "Wisconsin", Region = "Midwest" },
        new State { StateId = 50, Name = "Wyoming", Region = "West" }
      );
      builder.Entity<Park>().HasData(
        new Park { ParkId = 1, Name = "Gulf State Park", IsNational = false, StateId = 1 },
        new Park { ParkId = 2, Name = "Russel Cave National Monument", IsNational = true, StateId = 1 },
        new Park { ParkId = 3, Name = "Chugach State Park", IsNational = false, StateId = 2 },
        new Park { ParkId = 4, Name = "Kena Fjords National Park", IsNational = true, StateId = 2 },
        new Park { ParkId = 5, Name = "Cattali Cove State Park", IsNational = false, StateId = 3 },
        new Park { ParkId = 6, Name = "Grand Canyon National Park", IsNational = true, StateId = 3 },
        new Park { ParkId = 7, Name = "Queen Wilhelmina State Park", IsNational = false, StateId = 4 },
        new Park { ParkId = 8, Name = "Hot Springs National Park", IsNational = true, StateId = 4 },
        new Park { ParkId = 9, Name = "Calaveras Big Trees State Park", IsNational = false, StateId = 5 },
        new Park { ParkId = 10, Name = "Yosemite National Park", IsNational = true, StateId = 5 },
        // new Park { Name = "", IsNational = false, StateId = 6 },
        // new Park { Name = "", IsNational = true, StateId = 6 },
        // new Park { Name = "", IsNational = false, StateId = 7 },
        // new Park { Name = "", IsNational = true, StateId = 7 },
        // new Park { Name = "", IsNational = false, StateId = 8 },
        // new Park { Name = "", IsNational = true, StateId = 8 },
        // new Park { Name = "", IsNational = false, StateId = 9 },
        // new Park { Name = "", IsNational = true, StateId = 9 },
        // new Park { Name = "", IsNational = false, StateId = 10 },
        // new Park { Name = "", IsNational = true, StateId = 10 },
        // new Park { Name = "", IsNational = false, StateId = 11 },
        // new Park { Name = "", IsNational = true, StateId = 11 },
        // new Park { Name = "", IsNational = false, StateId = 12 },
        // new Park { Name = "", IsNational = true, StateId = 12 },
        // new Park { Name = "", IsNational = false, StateId = 13 },
        // new Park { Name = "", IsNational = true, StateId = 13 },
        // new Park { Name = "", IsNational = false, StateId = 14 },
        // new Park { Name = "", IsNational = true, StateId = 14 },
        // new Park { Name = "", IsNational = false, StateId = 15 },
        // new Park { Name = "", IsNational = true, StateId = 15 },
        // new Park { Name = "", IsNational = false, StateId = 16 },
        // new Park { Name = "", IsNational = true, StateId = 16 },
        // new Park { Name = "", IsNational = false, StateId = 17 },
        // new Park { Name = "", IsNational = true, StateId = 17 },
        // new Park { Name = "", IsNational = false, StateId = 18 },
        // new Park { Name = "", IsNational = true, StateId = 18 },
        // new Park { Name = "", IsNational = false, StateId = 19 },
        // new Park { Name = "", IsNational = true, StateId = 19 },
        // new Park { Name = "", IsNational = false, StateId = 20 },
        // new Park { Name = "", IsNational = true, StateId = 20 },
        // new Park { Name = "", IsNational = false, StateId = 21 },
        // new Park { Name = "", IsNational = true, StateId = 21 },
        // new Park { Name = "", IsNational = false, StateId = 22 },
        // new Park { Name = "", IsNational = true, StateId = 22 },
        // new Park { Name = "", IsNational = false, StateId = 23 },
        // new Park { Name = "", IsNational = true, StateId = 23 },
        // new Park { Name = "", IsNational = false, StateId = 24 },
        // new Park { Name = "", IsNational = true, StateId = 24 },
        // new Park { Name = "", IsNational = false, StateId = 25 },
        // new Park { Name = "", IsNational = true, StateId = 25 },
        // new Park { Name = "", IsNational = false, StateId = 26 },
        // new Park { Name = "", IsNational = true, StateId = 26 },
        // new Park { Name = "", IsNational = false, StateId = 27 },
        // new Park { Name = "", IsNational = true, StateId = 27 },
        // new Park { Name = "", IsNational = false, StateId = 28 },
        // new Park { Name = "", IsNational = true, StateId = 28 },
        // new Park { Name = "", IsNational = false, StateId = 29 },
        // new Park { Name = "", IsNational = true, StateId = 29 },
        // new Park { Name = "", IsNational = false, StateId = 30 },
        // new Park { Name = "", IsNational = true, StateId = 30 },
        // new Park { Name = "", IsNational = false, StateId = 31 },
        // new Park { Name = "", IsNational = true, StateId = 31 },
        new Park { ParkId = 11, Name = "Letchworth State Park", IsNational = false, StateId = 32 },
        new Park { ParkId = 12, Name = "Liberty Island", IsNational = true, StateId = 32 },
        // new Park { Name = "", IsNational = false, StateId = 33 },
        // new Park { Name = "", IsNational = true, StateId = 33 },
        // new Park { Name = "", IsNational = false, StateId = 34 },
        // new Park { Name = "", IsNational = true, StateId = 34 },
        // new Park { Name = "", IsNational = false, StateId = 35 },
        // new Park { Name = "", IsNational = true, StateId = 35 },
        // new Park { Name = "", IsNational = false, StateId = 36 },
        // new Park { Name = "", IsNational = true, StateId = 36 },
        // new Park { Name = "", IsNational = false, StateId = 37 },
        // new Park { Name = "", IsNational = true, StateId = 37 },
        // new Park { Name = "", IsNational = false, StateId = 38 },
        // new Park { Name = "", IsNational = true, StateId = 38 },
        // new Park { Name = "", IsNational = false, StateId = 39 },
        // new Park { Name = "", IsNational = true, StateId = 39 },
        // new Park { Name = "", IsNational = false, StateId = 40 },
        // new Park { Name = "", IsNational = true, StateId = 40 },
        // new Park { Name = "", IsNational = false, StateId = 41 },
        // new Park { Name = "", IsNational = true, StateId = 41 },
        // new Park { Name = "", IsNational = false, StateId = 42 },
        // new Park { Name = "", IsNational = true, StateId = 42 },
        // new Park { Name = "", IsNational = false, StateId = 43 },
        // new Park { Name = "", IsNational = true, StateId = 43 },
        // new Park { Name = "", IsNational = false, StateId = 44 },
        // new Park { Name = "", IsNational = true, StateId = 44 },
        // new Park { Name = "", IsNational = false, StateId = 45 },
        // new Park { Name = "", IsNational = true, StateId = 45 },
        // new Park { Name = "", IsNational = false, StateId = 46 },
        // new Park { Name = "", IsNational = true, StateId = 46 },
        new Park { ParkId = 13, Name = "Saint Edward State Park", IsNational = false, StateId = 47 },
        new Park { ParkId = 14, Name = "Olympic National Park", IsNational = true, StateId = 47 }
        // new Park { Name = "", IsNational = false, StateId = 48 },
        // new Park { Name = "", IsNational = true, StateId = 48 },
        // new Park { Name = "", IsNational = false, StateId = 49 },
        // new Park { Name = "", IsNational = true, StateId = 49 },
        // new Park { Name = "", IsNational = false, StateId = 50 },
        // new Park { Name = "", IsNational = true, StateId = 50 }
        );
    }
  }
}
