// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Helpers;

namespace parksapi.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    partial class ParksApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksApi.Entities.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsNational")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.ToTable("park");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            IsNational = false,
                            Name = "Gulf State Park",
                            StateId = 1,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 2,
                            IsNational = true,
                            Name = "Russel Cave National Monument",
                            StateId = 1,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 3,
                            IsNational = false,
                            Name = "Chugach State Park",
                            StateId = 2,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 4,
                            IsNational = true,
                            Name = "Kena Fjords National Park",
                            StateId = 2,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 5,
                            IsNational = false,
                            Name = "Cattali Cove State Park",
                            StateId = 3,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 6,
                            IsNational = true,
                            Name = "Grand Canyon National Park",
                            StateId = 3,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 7,
                            IsNational = false,
                            Name = "Queen Wilhelmina State Park",
                            StateId = 4,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 8,
                            IsNational = true,
                            Name = "Hot Springs National Park",
                            StateId = 4,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 9,
                            IsNational = false,
                            Name = "Calaveras Big Trees State Park",
                            StateId = 5,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 10,
                            IsNational = true,
                            Name = "Yosemite National Park",
                            StateId = 5,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 11,
                            IsNational = false,
                            Name = "Letchworth State Park",
                            StateId = 32,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 12,
                            IsNational = true,
                            Name = "Liberty Island",
                            StateId = 32,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 13,
                            IsNational = false,
                            Name = "Saint Edward State Park",
                            StateId = 47,
                            UserId = 0
                        },
                        new
                        {
                            ParkId = 14,
                            IsNational = true,
                            Name = "Olympic National Park",
                            StateId = 47,
                            UserId = 0
                        });
                });

            modelBuilder.Entity("ParksApi.Entities.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Region")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("StateId");

                    b.ToTable("state");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            Name = "Alabama",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 2,
                            Name = "Alaska",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 3,
                            Name = "Arizona",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 4,
                            Name = "Arkansas",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 5,
                            Name = "California",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 6,
                            Name = "Colorado",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 7,
                            Name = "Connecticut",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 8,
                            Name = "Delaware",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 9,
                            Name = "Florida",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 10,
                            Name = "Georgia",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 11,
                            Name = "Hawaii",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 12,
                            Name = "Idaho",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 13,
                            Name = "Illinois",
                            Region = "Midwest"
                        },
                        new
                        {
                            StateId = 14,
                            Name = "Indiana",
                            Region = "Midwest"
                        },
                        new
                        {
                            StateId = 15,
                            Name = "Iowa",
                            Region = "Midwest"
                        },
                        new
                        {
                            StateId = 16,
                            Name = "Kansas",
                            Region = "Midwest"
                        },
                        new
                        {
                            StateId = 17,
                            Name = "Kentucky",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 18,
                            Name = "Louisiana",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 19,
                            Name = "Maine",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 20,
                            Name = "Maryland",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 21,
                            Name = "Massachusetts",
                            Region = "Northeast"
                        },
                        new
                        {
                            StateId = 22,
                            Name = "Michigan",
                            Region = "Midwest"
                        },
                        new
                        {
                            StateId = 23,
                            Name = "Minnesota",
                            Region = "Midwest"
                        },
                        new
                        {
                            StateId = 24,
                            Name = "Mississippi",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 25,
                            Name = "Missouri",
                            Region = "Midwest"
                        },
                        new
                        {
                            StateId = 26,
                            Name = "Montana",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 27,
                            Name = "Nebraska",
                            Region = "Midwest"
                        },
                        new
                        {
                            StateId = 28,
                            Name = "Nevada",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 29,
                            Name = "New Hampshire",
                            Region = "Northeast"
                        },
                        new
                        {
                            StateId = 30,
                            Name = "New Jersey",
                            Region = "Northeast"
                        },
                        new
                        {
                            StateId = 31,
                            Name = "New Mexico",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 32,
                            Name = "New York",
                            Region = "Northeast"
                        },
                        new
                        {
                            StateId = 33,
                            Name = "North Carolina",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 34,
                            Name = "North Dakota",
                            Region = "Midwest"
                        },
                        new
                        {
                            StateId = 35,
                            Name = "Ohio",
                            Region = "Midwest"
                        },
                        new
                        {
                            StateId = 36,
                            Name = "Oklahoma",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 37,
                            Name = "Oregon",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 38,
                            Name = "Pennsylvania",
                            Region = "Northeast"
                        },
                        new
                        {
                            StateId = 39,
                            Name = "Rhode Island",
                            Region = "Northeast"
                        },
                        new
                        {
                            StateId = 40,
                            Name = "South Carolina",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 41,
                            Name = "South Dakota",
                            Region = "Midwest"
                        },
                        new
                        {
                            StateId = 42,
                            Name = "Tennessee",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 43,
                            Name = "Texas",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 44,
                            Name = "Utah",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 45,
                            Name = "Vermont",
                            Region = "Northeast"
                        },
                        new
                        {
                            StateId = 46,
                            Name = "Virginia",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 47,
                            Name = "Washington",
                            Region = "West"
                        },
                        new
                        {
                            StateId = 48,
                            Name = "West Virginia",
                            Region = "South"
                        },
                        new
                        {
                            StateId = 49,
                            Name = "Wisconsin",
                            Region = "Midwest"
                        },
                        new
                        {
                            StateId = 50,
                            Name = "Wyoming",
                            Region = "West"
                        });
                });

            modelBuilder.Entity("ParksApi.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob");

                    b.Property<string>("Role")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Token")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
