// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Helpers;

namespace parksapi.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    partial class ParksApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksApi.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("ParksApi.Entities.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsNational")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("park");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsNational = false,
                            Name = "Gulf State Park",
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsNational = true,
                            Name = "Russel Cave National Monument",
                            StateId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsNational = false,
                            Name = "Chugach State Park",
                            StateId = 2
                        },
                        new
                        {
                            Id = 4,
                            IsNational = true,
                            Name = "Kena Fjords National Park",
                            StateId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsNational = false,
                            Name = "Cattali Cove State Park",
                            StateId = 3
                        },
                        new
                        {
                            Id = 6,
                            IsNational = true,
                            Name = "Grand Canyon National Park",
                            StateId = 3
                        },
                        new
                        {
                            Id = 7,
                            IsNational = false,
                            Name = "Queen Wilhelmina State Park",
                            StateId = 4
                        },
                        new
                        {
                            Id = 8,
                            IsNational = true,
                            Name = "Hot Springs National Park",
                            StateId = 4
                        },
                        new
                        {
                            Id = 9,
                            IsNational = false,
                            Name = "Calaveras Big Trees State Park",
                            StateId = 5
                        },
                        new
                        {
                            Id = 10,
                            IsNational = true,
                            Name = "Yosemite National Park",
                            StateId = 5
                        },
                        new
                        {
                            Id = 11,
                            IsNational = false,
                            Name = "Letchworth State Park",
                            StateId = 32
                        },
                        new
                        {
                            Id = 12,
                            IsNational = true,
                            Name = "Liberty Island",
                            StateId = 32
                        },
                        new
                        {
                            Id = 13,
                            IsNational = false,
                            Name = "Saint Edward State Park",
                            StateId = 47
                        },
                        new
                        {
                            Id = 14,
                            IsNational = true,
                            Name = "Olympic National Park",
                            StateId = 47
                        });
                });

            modelBuilder.Entity("ParksApi.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ParkId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("review");
                });

            modelBuilder.Entity("ParksApi.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Region")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("state");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alabama",
                            Region = "South"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alaska",
                            Region = "West"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Arizona",
                            Region = "West"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Arkansas",
                            Region = "South"
                        },
                        new
                        {
                            Id = 5,
                            Name = "California",
                            Region = "West"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Colorado",
                            Region = "West"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Connecticut",
                            Region = "West"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Delaware",
                            Region = "South"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Florida",
                            Region = "South"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Georgia",
                            Region = "South"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Hawaii",
                            Region = "West"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Idaho",
                            Region = "West"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Illinois",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Indiana",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Iowa",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Kansas",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Kentucky",
                            Region = "South"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Louisiana",
                            Region = "South"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Maine",
                            Region = "West"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Maryland",
                            Region = "South"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Massachusetts",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Michigan",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Minnesota",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Mississippi",
                            Region = "South"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Missouri",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Montana",
                            Region = "West"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Nebraska",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Nevada",
                            Region = "West"
                        },
                        new
                        {
                            Id = 29,
                            Name = "New Hampshire",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 30,
                            Name = "New Jersey",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 31,
                            Name = "New Mexico",
                            Region = "West"
                        },
                        new
                        {
                            Id = 32,
                            Name = "New York",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 33,
                            Name = "North Carolina",
                            Region = "South"
                        },
                        new
                        {
                            Id = 34,
                            Name = "North Dakota",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Ohio",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Oklahoma",
                            Region = "South"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Oregon",
                            Region = "West"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Pennsylvania",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Rhode Island",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 40,
                            Name = "South Carolina",
                            Region = "South"
                        },
                        new
                        {
                            Id = 41,
                            Name = "South Dakota",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Tennessee",
                            Region = "South"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Texas",
                            Region = "South"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Utah",
                            Region = "West"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Vermont",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Virginia",
                            Region = "South"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Washington",
                            Region = "West"
                        },
                        new
                        {
                            Id = 48,
                            Name = "West Virginia",
                            Region = "South"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Wisconsin",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Wyoming",
                            Region = "West"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
